### ISSUE TITLE
Clang should error if an undeclared enclave is used

### ISSUE THREAD

**Issue by protoben** [GaloisInc/pirate-llvm#1]
Presently, the following code compiles without error and errors out at the linker:

```c
#pragma enclave declare(orange)

int sensor_manager_main(int argc, char *argv[])
     __attribute__((gaps_enclave_main("purple")))
{ ... }
```

It would be better if this errored out at the compilation stage, both because clang has friendlier error reporting than llvm, and because it would encourage users to declare enclaves in shared headers.

**Comment by glguy** [comment]
Fixed in b21b0f12322a3ccdf95260f92c96e0cf4e08d5d7
