### ISSUE TITLE
lld segentation fault when compiling pirate-demos

### ISSUE THREAD

**Issue by joehendrix** [GaloisInc/pirate-llvm#10]
There seems to be a segmentation fault when compiling pirate-demos.  I suspect it is related to a mixture of object files with gaps and without gaps information.

A script is here: https://github.com/GaloisInc/pirate/pull/17/checks?check_run_id=480168162

**Comment by mspiegel** [comment]
I see some instances of the string literal ".gaps.enclaves" in lld/ELF/Driver.cpp, llvm/lib/MC/ELFObjectWriter.cpp, and llvm/tools/llvm-readobj/ELFDumper.cpp. Not sure if related to the issue.
